name: Release Darwinia

on:
  push:
    branches: 
      - crab
      - darwinia
  #   tags:
  #     - "v*"
  # workflow_dispatch:


env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  publish-docker-image:
    name: Publish 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha

      - uses: olegtarasov/get-tag@v2.1
        id: tag-name

      - name: Build with sha
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:sha-${{ steps.short-sha.outputs.sha }}
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:staging

      - name: Build with tag
        uses: docker/build-push-action@v3
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:${{ steps.tag-name.outputs.tag }}
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:latest
